import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '../components/header'
import Navbar from '../components/navbar'
import Footer from '../components/footer'
import logo from '../public/Frame.ico'
import Button from 'react-bootstrap/Button';
import Emoji1 from '../public/🤓.ico'
import Emoji2 from '../public/🥰.ico'
import Emoji3 from '../public/🥳.ico'
import ima from '../public/images.ico'
import Usesignin from '../customhook/signuphook'





const inter = Inter({ subsets: ['latin'] })

export default function Home() {


  const{


    changing,
    setchanging,
    signuphandler
    
 
 
 } = Usesignin()
 {console.log(changing);
 }


  return (
    <>
      <Head>
        <title>Sololearn</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      

<Header/>

      <main>


        <div className=' justify-content-center pt-5 ' style={{ marginTop: 40, }}>

          <div className='d-flex justify-content-center'>

            <h1 className='  col-9 col-sm-10' style={{ fontSize: '5vw', textAlign: 'center', marginBottom: '5vh', }}>Work at Sololearn. We change lives <br /> by teaching people .</h1>

          </div>

          <div className='d-flex justify-content-center'>

            <p className='col-3 col-sm-8' style={{ fontSize: '1.5vw', textAlign: 'center', color: '#6B7F99', }}>We are on a mission to build the most fun and effective learning experience <br /> that bridges skills to future careers. Join us!</p>

           
          </div>

          <div className='d-flex justify-content-center ' >
              <Button variant="" className='  px-4  text-light rounded-5' style={{ backgroundColor: '#2493DF', padding: '1vw', fontSize: '1vw', marginTop: '5vh', marginBottom: '20vh', }}>View open positions</Button>
            </div>

        </div>



        <div style={{ background: '#F2F5F7', paddingBottom: '10vh', }}>


          <p style={{ fontSize: '4vw', paddingTop: '5vw', paddingBottom: '6vh', }} className='d-flex justify-content-center fw-5'>You want to make a difference.</p>


          <div className=' px-5 d-flex justify-content-center' style={{ paddingLeft: '3vw', paddingRight: '3vw', }}>



            <div className="row row-cols-1 row-cols-md-3 g-5  " style={{ display: 'flex', justifyContent: 'center', }}>
              <div className="col border border-light px-5">
                <div className="card border-light h-100">
                  <Image src={Emoji3} className="card-img-top " alt="..." style={{ width: '5vh', display: "flex", alignSelf: 'center', marginTop: '2vh', }} />
                  <div className="card-body p-5">
                    <h3 className="card-title  mb-4" style={{ textAlign: 'center', }}>Your work matters.</h3>
                    <p className="card-text fs-5" style={{ textAlign: 'center', color: '#6B7F99', }} >Over 60% of new jobs worldwide will require technical skills. Your work has a direct impact on people’s lives.</p>
                  </div>

                </div>
              </div>
              <div className="col px-5">
                <div className="card border-light h-100">
                  <Image src={Emoji2} className="card-img-top" alt="..." style={{ width: '5vh', display: "flex", alignSelf: 'center', marginTop: '2vh', }} />
                  <div className="card-body p-5">
                    <h3 className="card-title mb-4" style={{ textAlign: 'center', }}>We care about you.</h3>
                    <p className="card-text fs-5" style={{ textAlign: 'center', color: '#6B7F99', }}>We’re building a global company that invests in its staff. A worthy mission, competitive salary & benefits, a supportive community, and worldwide travel set us apart.</p>
                  </div>

                </div>
              </div>


              <div className="col px-5">
                <div className="card border-light h-100">
                  <Image src={Emoji1} className="card-img-top  " alt="..." style={{ width: '5vh', display: "flex", alignSelf: 'center', marginTop: '2vh', }} />
                  <div className="card-body p-5">
                    <h3 className="card-title mb-4" style={{ textAlign: 'center', }}>You’re passionate.</h3>
                    <p className="card-text fs-5" style={{ textAlign: 'center', color: '#6B7F99', }}>We’re a values-driven learning company and believe in continuous improvement for our products and for our team members. The sky’s the limit.</p>
                  </div>

                </div>
              </div>
            </div>

          </div>


        </div>


        <div className='p-5' style={{ padding: '5vw', }}>

          <p className='fs-5' style={{ textAlign: 'center', color: '#6B7F99', }}>“We launched Sololearn in 2014 to change the way people learn. We started on mobile devices so we <br /> could reach as many people around the globe as possible. Years later, we’re still here and have <br /> helped over 20 million people learn how to code.”</p>


        </div>



        <div style={{ background: '#F2F5F7' }}>


          <p style={{ fontSize: '6vh', paddingTop: '10vw', paddingBottom: '2vh', textAlign:'center', }} className='d-flex  justify-content-center fw-5'>You’ll really like working here.</p>



          <div className='px-5'>
            <p className='' style={{ fontSize: '2.5vh', textAlign: 'center', color: '#6B7F99', }}>Not to brag (much!) but we were awarded the 2021 Best Computer Coding Education <br /> Solution, EdTech Breakthrough Winner, and the 2021 America’s Best Startup <br /> Employers Award. Join our global team and meet Sololearners all over the world.</p>
          </div>


          <div className='d-flex justify-content-center'>


            <Image src={ima} className="  mb-5 pb-5   col-sm-5 col-12  " alt="..." style={{  marginTop: '3vh', }} />

          </div>


        </div>



        <div style={{ background: '#1F1E28',   }} className=" border-bottom border-1  border-secondary pb-5" >

          <p style={{ fontSize: '4vw', paddingTop: '5vw', color: 'white', textAlign: 'center', }} className=' fw-5'>Do we sound like a good fit? <br /> Check out our open positions.</p>

          <div className='d-flex justify-content-center'>
            <Button variant="" className='  px-4  text-light rounded-2 ' style={{ backgroundColor: '#2493DF', padding: '1vw', fontSize: '2vh', marginTop: '5vh', textAlign:'center', }}>View open positions</Button>

          </div>


        </div>


      </main>







      <Footer />
    </>
  )
}
